---
- name: Setup vpn client
  hosts: DOMO
  connection: local
  become: yes
  vars:
    # Use system python so apt apckage is available
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
#  - debug: var=hostvars['localhost']
  - name: Install wireguard package
    apt: 
     name: wireguard
     state: present
     update_cache: yes

  - name: Generate private key
    shell:
      cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > publickey
      chdir: /etc/wireguard
      creates: /etc/wireguard/publickey

  - name: Get public key
    command: cat /etc/wireguard/publickey
    register: publickey_contents
    changed_when: False

  - name: Just checking publickey
    debug:
      msg: "{{ publickey_contents }}"
  - name: Save public key as fact
    set_fact:
      pubkey: "{{ publickey_contents.stdout }}"

  - name: Create wireguard client config
    template:
      dest: /etc/wireguard/wg0.conf
      src: client_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'   
#    notify: restart wireguard

  handlers:
  - name : Restart wireguard
    shell: wg-quick down wg0; wg-quick up wg0
    args:
      executable: /bin/bash

- name: Setup vpn server
  hosts: TEST
  become: yes
  tasks: 
  - name: Install wireguard package
    apt:
      name: wireguard
      state: present
      update_cache: yes
  - name: Create server config wireguard
    template:
      dest: /etc/wireguard/wg0.conf
      src: server_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'
    notify: Reload wireguard config
  - name: Enable and persist ip forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      sysctl_set: yes
      reload: yes
  - name: Start wireguard and enable on boot
    systemd:
      name: wg-quick@wg0
      enabled: yes
      state: started
  handlers:
    - name : Reload wireguard config
      shell: wg syncconf wg0 <(wg-quick strip wg0)
      args:
        executable: /bin/bash

- name: Start VPN client 
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name : Start vpn service
    command: wg-quick up wg0 
