---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

- hosts: DOMO
  become: true
#  connection: local
  roles:
    - client

#- hosts: TEST
#  become: true
#  connection: local
#  roles:
#    - server


#  vars:
    # Use system python so apt apckage is available
#    ansible_python_interpreter: "/usr/bin/env python"
#  tasks:
#  - debug: var=hostvars['localhost']

- name: Start VPN client 
  hosts: DOMO
  connection: local
  become: yes
  tasks:
  - name : Start vpn service
    command: wg-quick up wg0 
