---
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

- hosts: DOMO
  become: true
  roles:
    - client

- hosts: TEST
  become: true
  roles:
    - server


#  tasks:
#  - debug: var=hostvars['localhost']

- name: Start VPN client 
  hosts: DOMO
  become: yes
  tasks:
  - name : Start vpn service
    command: wg-quick up wg0 
    when: client_wireguard_config.changed
